module CSS (cssStyles, themeScript) where

-- Minimalist theme: hairlines, generous whitespace, restrained color.
-- Dark is the default; light overrides via [data-theme="light"].
cssStyles :: String
cssStyles = unlines
  [ "    :root {"
  , "      --bg: #101114;"
  , "      --paper: #17181c;"
  , "      --ink: #e9e9ec;"
  , "      --muted: #8b8d96;"
  , "      --faint: #5c5e66;"
  , "      --line: #26272c;"
  , "      --accent: #7aa2f7;"
  , "      --accent-2: #e0af68;"
  , "      --section: #9ece6a;"
  , "      --chip: #1d1e23;"
  , "      --shadow: rgba(0,0,0,.5);"
  , "      --serif: 'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, serif;"
  , "      --sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;"
  , "      --mono: 'JetBrains Mono', 'SF Mono', 'Cascadia Code', Consolas, 'Liberation Mono', monospace;"
  , "    }"
  , "    [data-theme=\"light\"] {"
  , "      --bg: #f7f7f5;"
  , "      --paper: #ffffff;"
  , "      --ink: #1c1c1f;"
  , "      --muted: #6b6d75;"
  , "      --faint: #9a9ca3;"
  , "      --line: #e4e4e1;"
  , "      --accent: #3b63c4;"
  , "      --accent-2: #b3761b;"
  , "      --section: #3d8b40;"
  , "      --chip: #f2f2ef;"
  , "      --shadow: rgba(30,30,40,.12);"
  , "    }"
  , "    * { box-sizing: border-box; margin: 0; padding: 0; }"
  , "    html { -webkit-text-size-adjust: 100%; }"
  , "    body {"
  , "      background: var(--paper);"
  , "      color: var(--ink);"
  , "      font-family: var(--sans);"
  , "      line-height: 1.5;"
  , "      padding: 1.5rem 5vw 2.5rem;"
  , "      min-height: 100vh;"
  , "      display: flex;"
  , "      flex-direction: column;"
  , "      transition: background .25s ease, color .25s ease;"
  , "    }"
  , "    .sheet {"
  , "      width: 100%;"
  , "      max-width: 80rem;"
  , "      margin: 0 auto;"
  , "      background: transparent;"
  , "      border: none;"
  , "      border-radius: 0;"
  , "      padding: 0;"
  , "      box-shadow: none;"
  , "      position: relative;"
  , "      display: flex;"
  , "      flex-direction: column;"
  , "      flex: 1;"
  , "    }"
  , ""
  , "    /* Theme toggle */"
  , "    .theme-toggle {"
  , "      position: absolute;"
  , "      top: 0;"
  , "      right: 0;"
  , "      width: 2.2rem;"
  , "      height: 2.2rem;"
  , "      border: 1px solid var(--line);"
  , "      border-radius: 50%;"
  , "      background: var(--chip);"
  , "      color: var(--muted);"
  , "      font-size: 1rem;"
  , "      line-height: 1;"
  , "      cursor: pointer;"
  , "      display: flex;"
  , "      align-items: center;"
  , "      justify-content: center;"
  , "      transition: color .2s ease, border-color .2s ease, transform .3s ease;"
  , "      z-index: 10;"
  , "    }"
  , "    .theme-toggle:hover { color: var(--accent); border-color: var(--accent); transform: rotate(20deg); }"
  , "    .icon-sun, .icon-moon { display: none; }"
  , "    [data-theme=\"dark\"] .icon-moon { display: inline; }"
  , "    [data-theme=\"light\"] .icon-sun { display: inline; }"
  , ""
  , "    /* Header: side-by-side flexbox row style */"
  , "    .song-header {"
  , "      display: flex;"
  , "      flex-wrap: wrap;"
  , "      align-items: baseline;"
  , "      gap: 1rem 2rem;"
  , "      margin-bottom: 1.2rem;"
  , "      padding-right: 3rem; /* room for theme toggle */"
  , "      border-bottom: 1px solid var(--line);"
  , "      padding-bottom: .8rem;"
  , "    }"
  , "    .header-main {"
  , "      display: inline-flex;"
  , "      flex-wrap: wrap;"
  , "      align-items: baseline;"
  , "      gap: .75rem 1rem;"
  , "    }"
  , "    .song-title {"
  , "      font-family: var(--serif);"
  , "      font-size: 1.6rem;"
  , "      font-weight: 600;"
  , "      letter-spacing: -.01em;"
  , "      line-height: 1.2;"
  , "    }"
  , "    .song-artist {"
  , "      color: var(--muted);"
  , "      font-size: .95rem;"
  , "      font-style: italic;"
  , "      font-family: var(--serif);"
  , "    }"
  , "    .song-badges {"
  , "      display: inline-flex;"
  , "      flex-wrap: wrap;"
  , "      align-items: center;"
  , "      gap: .6rem 1.2rem;"
  , "      margin-left: auto;"
  , "    }"
  , "    .badge {"
  , "      font-size: .74rem;"
  , "      letter-spacing: .04em;"
  , "      color: var(--ink);"
  , "      display: inline-flex;"
  , "      align-items: baseline;"
  , "      gap: .35rem;"
  , "    }"
  , "    .badge-label {"
  , "      color: var(--faint);"
  , "      font-size: .62rem;"
  , "      font-weight: 700;"
  , "      letter-spacing: .14em;"
  , "      text-transform: uppercase;"
  , "    }"

  , "    /* Sections & flexbox multi-column layout: side-by-side columns on wide screens */"
  , "    .song-content {"
  , "      display: flex;"
  , "      flex-direction: row;"
  , "      justify-content: center; /* Horizontally centered */"
  , "      align-items: flex-start;"
  , "      gap: 3.5rem;"
  , "      width: 100%;"
  , "      margin: 0 auto;"
  , "    }"
  , "    .song-column {"
  , "      flex: 0 1 auto;"
  , "      width: 26rem;"
  , "      max-width: 34rem;"
  , "      min-width: 18rem;"
  , "      display: flex;"
  , "      flex-direction: column;"
  , "      gap: 1.35rem;"
  , "    }"
  , "    .section-title {"
  , "      font-size: .72rem;"
  , "      font-weight: 700;"
  , "      letter-spacing: .22em;"
  , "      text-transform: uppercase;"
  , "      color: var(--section);"
  , "      margin-top: .6rem;"
  , "      margin-bottom: 0;"
  , "      padding-bottom: .35rem;"
  , "      border-bottom: 1px solid var(--line);"
  , "    }"
  , "    .section-title:first-child {"
  , "      margin-top: 0;"
  , "    }"
  , ""
  , "    /* Chord + lyric rows: each line is an independent flex unit */"
  , "    .chord-lyric-row, .chord-only-row, .lyric-only-row {"
  , "      width: 100%;"
  , "    }"
  , "    .chord-lyric-row {"
  , "      display: flex;"
  , "      flex-wrap: wrap;"
  , "      align-items: flex-end;"
  , "      line-height: 1.35;"
  , "    }"
  , "    .chord-lyric-pair {"
  , "      display: inline-flex;"
  , "      flex-direction: column;"
  , "      white-space: pre;"
  , "    }"
  , "    .chord {"
  , "      color: var(--accent);"
  , "      font-weight: 600;"
  , "      font-size: .88rem;"
  , "      line-height: 1.45;"
  , "      min-height: 1.5em;"
  , "      letter-spacing: .01em;"
  , "      user-select: none;"
  , "    }"
  , "    .chord-custom { color: var(--accent-2); }"
  , "    .chord-spacer { min-height: 1.5em; visibility: hidden; }"
  , "    .lyric { color: var(--ink); white-space: pre; }"
  , "    .chord-only-row {"
  , "      display: flex;"
  , "      flex-wrap: wrap;"
  , "      gap: 1.5rem;"
  , "      color: var(--accent);"
  , "      font-weight: 600;"
  , "      padding: .15rem 0;"
  , "    }"
  , "    .lyric-only-row { color: var(--ink); }"
  , ""
  , "    /* Hover diagram popover */"
  , "    .chord-with-hover {"
  , "      position: relative;"
  , "      display: inline-block;"
  , "      cursor: pointer;"
  , "      -webkit-tap-highlight-color: transparent;"
  , "    }"
  , "    .chord-popover {"
  , "      position: absolute;"
  , "      bottom: calc(100% + 10px);"
  , "      left: 50%;"
  , "      transform: translateX(-50%) translateY(4px);"
  , "      background: var(--paper);"
  , "      border: 1px solid var(--line);"
  , "      border-radius: 6px;"
  , "      padding: .55rem .6rem .45rem;"
  , "      box-shadow: 0 14px 34px -12px var(--shadow);"
  , "      z-index: 100;"
  , "      visibility: hidden;"
  , "      opacity: 0;"
  , "      transition: opacity .16s ease, transform .16s ease, visibility .16s;"
  , "      pointer-events: none;"
  , "    }"
  , "    .chord-popover::after {"
  , "      content: '';"
  , "      position: absolute;"
  , "      top: 100%;"
  , "      left: 50%;"
  , "      transform: translateX(-50%);"
  , "      border: 6px solid transparent;"
  , "      border-top-color: var(--line);"
  , "    }"
  , "    .chord-with-hover:hover .chord-popover,"
  , "    .chord-with-hover.active-popover .chord-popover {"
  , "      visibility: visible;"
  , "      opacity: 1;"
  , "      transform: translateX(-50%) translateY(0);"
  , "    }"
  , "    .chord-popover-text {"
  , "      width: max-content;"
  , "      max-width: 13rem;"
  , "      padding: .7rem .8rem;"
  , "      color: var(--ink);"
  , "      font-family: var(--sans);"
  , "      font-size: .78rem;"
  , "      line-height: 1.35;"
  , "      text-align: center;"
  , "    }"
  , "    .chord-popover-text strong { display: block; color: var(--accent); margin-bottom: .25rem; }"
  , "    .chord-popover-text span { color: var(--muted); }"
  , "    .chord-diagram-svg { display: block; }"
  , ""
  , "    /* Chord palette: generated wherever {chords} / [Chords] is placed */"
  , "    .song-chords-palette {"
  , "      width: 100%;"
  , "      margin: 0.5rem auto 1.8rem;"
  , "      padding: 1rem 1.3rem;"
  , "      background: var(--chip);"
  , "      border: 1px solid var(--line);"
  , "      border-radius: 6px;"
  , "      display: flex;"
  , "      flex-direction: column;"
  , "      align-items: center;"
  , "      break-inside: avoid;"
  , "    }"
  , "    .palette-title {"
  , "      font-size: .68rem;"
  , "      font-weight: 600;"
  , "      letter-spacing: .2em;"
  , "      text-transform: uppercase;"
  , "      color: var(--faint);"
  , "      margin-bottom: .8rem;"
  , "    }"
  , "    .palette-grid { display: flex; flex-wrap: wrap; gap: .75rem; justify-content: center; }"
  , "    .palette-item {"
  , "      border: 1px solid var(--line);"
  , "      border-radius: 4px;"
  , "      padding: .4rem .5rem .25rem;"
  , "      background: var(--paper);"
  , "      transition: border-color .18s ease, transform .18s ease;"
  , "    }"
  , "    .palette-item:hover { border-color: var(--accent); transform: translateY(-2px); }"
  , ""
  , "    /* Diagram colors follow the active theme */"
  , "    .chord-diagram-svg .grid-line { stroke: var(--line); }"
  , "    .chord-diagram-svg .nut-line { stroke: var(--ink); fill: var(--ink); }"
  , "    .chord-diagram-svg .diag-name { fill: var(--ink); font-family: var(--sans); font-weight: 600; }"
  , "    .chord-diagram-svg .diag-fret { fill: var(--muted); font-family: var(--mono); font-weight: 600; }"
  , "    .chord-diagram-svg .diag-dot { fill: var(--accent); }"
  , "    .chord-diagram-svg .diag-finger { fill: var(--paper); font-family: var(--mono); font-weight: 700; }"
  , "    .chord-diagram-svg .diag-open { stroke: var(--muted); }"
  , "    .chord-diagram-svg .diag-mute { fill: var(--accent-2); font-family: var(--mono); font-weight: 700; }"
  , ""
  , "    /* Mobile screens: single column, zero horizontal waste, touch-friendly */"
  , "    @media (max-width: 720px) {"
  , "      body { padding: 1rem .8rem 1.5rem; }"
  , "      .sheet {"
  , "        padding: 0;"
  , "      }"
  , "      .song-content {"
  , "        flex-direction: column;"
  , "        gap: 1.2rem;"
  , "      }"
  , "      .song-column {"
  , "        width: 100%;"
  , "        max-width: 100%;"
  , "        min-width: 0;"
  , "      }"
  , "      .theme-toggle {"
  , "        top: -.2rem;"
  , "        right: 0;"
  , "        width: 2rem;"
  , "        height: 2rem;"
  , "      }"
  , "      .song-header {"
  , "        flex-direction: column;"
  , "        align-items: flex-start;"
  , "        gap: .5rem;"
  , "        margin-bottom: 1.2rem;"
  , "        padding-right: 2.5rem;"
  , "      }"
  , "      .header-main {"
  , "        gap: .4rem .6rem;"
  , "      }"
  , "      .song-title {"
  , "        font-size: 1.35rem;"
  , "        line-height: 1.2;"
  , "      }"
  , "      .song-artist {"
  , "        font-size: .88rem;"
  , "        margin-top: 0;"
  , "      }"
  , "      .song-badges {"
  , "        margin-left: 0;"
  , "        gap: .4rem .8rem;"
  , "      }"
  , "      .badge {"
  , "        font-size: .68rem;"
  , "        padding: 0;"
  , "      }"
  , "      .section-title {"
  , "        font-size: .64rem;"
  , "        margin-top: .6rem;"
  , "        margin-bottom: .15rem;"
  , "      }"
  , "      .chord-lyric-row, .chord-only-row, .lyric-only-row {"
  , "        font-size: .88rem;"
  , "      }"
  , "      .chord { font-size: .82rem; }"
  , "      .chord-popover {"
  , "        bottom: calc(100% + 6px);"
  , "        max-width: calc(100vw - 2rem);"
  , "      }"
  , "      .song-chords-palette {"
  , "        padding: .85rem .95rem;"
  , "        margin: 1rem 0 1.5rem;"
  , "      }"
  , "      .palette-grid { gap: .55rem; }"
  , "    }"
  , "    @media print {"
  , "      /* Always print in light colors, whatever the screen theme is */"
  , "      :root, [data-theme=\"dark\"], [data-theme=\"light\"] {"
  , "        --bg: #ffffff;"
  , "        --paper: #ffffff;"
  , "        --ink: #111111;"
  , "        --muted: #555555;"
  , "        --faint: #888888;"
  , "        --line: #cccccc;"
  , "        --accent: #1a4fa0;"
  , "        --accent-2: #9a6212;"
  , "        --section: #1f6b32;"
  , "        --shadow: transparent;"
  , "      }"
  , "      body { background: #fff; padding: 0; }"
  , "      .sheet { box-shadow: none; border: none; max-width: 100%; padding: 0; }"
  , "      .theme-toggle { display: none; }"
  , "      .chord-popover { display: none; }"
  , "    }"

  ]

-- Inline script: defaults to system preference, persists the user choice, and supports mobile touch tap.
themeScript :: String
themeScript = unlines
  [ "(function(){"
  , "  var t=null;"
  , "  try{t=localStorage.getItem('chordbook-theme');}catch(e){}"
  , "  if(!t){t=window.matchMedia&&window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';}"
  , "  document.documentElement.setAttribute('data-theme',t);"
  , "})();"
  , "function toggleTheme(){"
  , "  var el=document.documentElement;"
  , "  var next=el.getAttribute('data-theme')==='light'?'dark':'light';"
  , "  el.setAttribute('data-theme',next);"
  , "  try{localStorage.setItem('chordbook-theme',next);}catch(e){}"
  , "}"
  , "document.addEventListener('click',function(e){"
  , "  var target=e.target.closest('.chord-with-hover');"
  , "  var all=document.querySelectorAll('.chord-with-hover.active-popover');"
  , "  for(var i=0;i<all.length;i++){"
  , "    if(all[i]!==target) all[i].classList.remove('active-popover');"
  , "  }"
  , "  if(target){"
  , "    target.classList.toggle('active-popover');"
  , "  }"
  , "});"
  , "function distributeSongColumns(){"
  , "  var container=document.getElementById('song-content');"
  , "  if(!container) return;"
  , "  if(!window._rawSongUnits){"
  , "    window._rawSongUnits=Array.from(container.children).map(function(el){return el.cloneNode(true);});"
  , "  }"
  , "  var units=window._rawSongUnits.map(function(el){return el.cloneNode(true);});"
  , "  var heights=units.map(function(u){"
  , "    return u.offsetHeight || (u.classList.contains('section-title') ? 34 : 52);"
  , "  });"
  , "  var topY=container.getBoundingClientRect().top;"
  , "  if(topY<=0) topY=200;"
  , "  var availH=window.innerHeight - topY - 35;"
  , "  if(availH<380) availH=380;"
  , "  var screenW=window.innerWidth;"
  , "  if(screenW<=720){"
  , "    container.innerHTML='';"
  , "    var col=document.createElement('div');"
  , "    col.className='song-column';"
  , "    col.style.maxWidth='100%';"
  , "    units.forEach(function(u){col.appendChild(u);});"
  , "    container.appendChild(col);"
  , "    return;"
  , "  }"
  , "  var colW=360; var colGap=56;"
  , "  var maxCols=Math.floor((container.clientWidth+colGap)/(colW+colGap));"
  , "  if(maxCols<1) maxCols=1;"
  , "  var rowGap=22;"
  , "  var cols=[]; var currentCol=[]; var currentH=0;"
  , "  for(var i=0;i<units.length;i++){"
  , "    var u=units[i];"
  , "    var h=heights[i]||50;"
  , "    var isTitle=u.classList.contains('section-title');"
  , "    var neededH=h+(currentCol.length>0?rowGap:0);"
  , "    if(isTitle&&i+1<units.length){"
  , "      neededH+=(heights[i+1]||50)+rowGap;"
  , "    }"
  , "    if(currentCol.length===0||(currentH+neededH<=availH)||cols.length>=maxCols-1){"
  , "      currentCol.push(u);"
  , "      currentH+=h+(currentCol.length>1?rowGap:0);"
  , "    }else{"
  , "      cols.push(currentCol);"
  , "      currentCol=[u];"
  , "      currentH=h;"
  , "    }"
  , "  }"
  , "  if(currentCol.length>0){"
  , "    cols.push(currentCol);"
  , "  }"
  , "  container.innerHTML='';"
  , "  cols.forEach(function(colUnits){"
  , "    var c=document.createElement('div');"
  , "    c.className='song-column';"
  , "    colUnits.forEach(function(u){c.appendChild(u);});"
  , "    container.appendChild(c);"
  , "  });"
  , "}"
  , "window.addEventListener('load',distributeSongColumns);"
  , "window.addEventListener('resize',distributeSongColumns);"
  , "if(document.readyState==='complete'||document.readyState==='interactive'){setTimeout(distributeSongColumns,0);}"
  ]
