module CSS (cssStyles, themeScript) where

-- Minimalist theme: hairlines, generous whitespace, restrained color.
-- Dark is the default; light overrides via [data-theme="light"].
cssStyles :: String
cssStyles = unlines
  [ "    :root {"
  , "      --bg: #101114;"
  , "      --paper: #17181c;"
  , "      --ink: #e9e9ec;"
  , "      --muted: #8b8d96;"
  , "      --faint: #5c5e66;"
  , "      --line: #26272c;"
  , "      --accent: #7aa2f7;"
  , "      --accent-2: #e0af68;"
  , "      --section: #9ece6a;"
  , "      --chip: #1d1e23;"
  , "      --shadow: rgba(0,0,0,.5);"
  , "      --serif: 'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, serif;"
  , "      --sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;"
  , "      --mono: 'JetBrains Mono', 'SF Mono', 'Cascadia Code', Consolas, 'Liberation Mono', monospace;"
  , "    }"
  , "    [data-theme=\"light\"] {"
  , "      --bg: #f7f7f5;"
  , "      --paper: #ffffff;"
  , "      --ink: #1c1c1f;"
  , "      --muted: #6b6d75;"
  , "      --faint: #9a9ca3;"
  , "      --line: #e4e4e1;"
  , "      --accent: #3b63c4;"
  , "      --accent-2: #b3761b;"
  , "      --section: #3d8b40;"
  , "      --chip: #f2f2ef;"
  , "      --shadow: rgba(30,30,40,.12);"
  , "    }"
  , "    * { box-sizing: border-box; margin: 0; padding: 0; }"
  , "    html { -webkit-text-size-adjust: 100%; }"
  , "    body {"
  , "      background: var(--bg);"
  , "      color: var(--ink);"
  , "      font-family: var(--sans);"
  , "      line-height: 1.6;"
  , "      padding: 4rem 1.5rem;"
  , "      display: flex;"
  , "      justify-content: center;"
  , "      transition: background .25s ease, color .25s ease;"
  , "    }"
  , "    .sheet {"
  , "      width: 100%;"
  , "      max-width: 46rem;"
  , "      background: var(--paper);"
  , "      border: 1px solid var(--line);"
  , "      border-radius: 4px;"
  , "      padding: 4rem 4.5rem 3.5rem;"
  , "      box-shadow: 0 18px 50px -20px var(--shadow);"
  , "      position: relative;"
  , "      transition: background .25s ease, border-color .25s ease;"
  , "    }"
  , ""
  , "    /* Theme toggle */"
  , "    .theme-toggle {"
  , "      position: absolute;"
  , "      top: 1.4rem;"
  , "      right: 1.6rem;"
  , "      width: 2.4rem;"
  , "      height: 2.4rem;"
  , "      border: 1px solid var(--line);"
  , "      border-radius: 50%;"
  , "      background: transparent;"
  , "      color: var(--muted);"
  , "      font-size: 1rem;"
  , "      line-height: 1;"
  , "      cursor: pointer;"
  , "      display: flex;"
  , "      align-items: center;"
  , "      justify-content: center;"
  , "      transition: color .2s ease, border-color .2s ease, transform .3s ease;"
  , "    }"
  , "    .theme-toggle:hover { color: var(--accent); border-color: var(--accent); transform: rotate(20deg); }"
  , "    .icon-sun, .icon-moon { display: none; }"
  , "    [data-theme=\"dark\"] .icon-moon { display: inline; }"
  , "    [data-theme=\"light\"] .icon-sun { display: inline; }"
  , ""
  , "    /* Header */"
  , "    .song-header { margin-bottom: 3.5rem; }"
  , "    .song-title {"
  , "      font-family: var(--serif);"
  , "      font-size: 2.6rem;"
  , "      font-weight: 500;"
  , "      letter-spacing: -.015em;"
  , "      line-height: 1.15;"
  , "    }"
  , "    .song-artist {"
  , "      color: var(--muted);"
  , "      font-size: 1.05rem;"
  , "      margin-top: .5rem;"
  , "      font-style: italic;"
  , "      font-family: var(--serif);"
  , "    }"
  , "    .song-badges {"
  , "      display: flex;"
  , "      flex-wrap: wrap;"
  , "      gap: 1.4rem;"
  , "      margin-top: 1.6rem;"
  , "      padding-top: 1.2rem;"
  , "      border-top: 1px solid var(--line);"
  , "    }"
  , "    .badge {"
  , "      font-size: .78rem;"
  , "      letter-spacing: .04em;"
  , "      color: var(--ink);"
  , "      display: inline-flex;"
  , "      align-items: baseline;"
  , "      gap: .45rem;"
  , "    }"
  , "    .badge-label {"
  , "      color: var(--faint);"
  , "      font-size: .66rem;"
  , "      font-weight: 600;"
  , "      letter-spacing: .14em;"
  , "      text-transform: uppercase;"
  , "    }"

  , "    /* Sections */"
  , "    .song-section { margin-bottom: 3rem; }"
  , "    .section-title {"
  , "      font-size: .72rem;"
  , "      font-weight: 600;"
  , "      letter-spacing: .22em;"
  , "      text-transform: uppercase;"
  , "      color: var(--section);"
  , "      margin-bottom: 1.5rem;"
  , "      display: flex;"
  , "      align-items: center;"
  , "      gap: .9rem;"
  , "    }"
  , "    .section-title::after {"
  , "      content: '';"
  , "      flex: 1;"
  , "      height: 1px;"
  , "      background: var(--line);"
  , "    }"
  , "    .section-lines {"
  , "      display: flex;"
  , "      flex-direction: column;"
  , "      gap: 1.6rem;"
  , "      font-family: var(--mono);"
  , "      font-size: .98rem;"
  , "      font-variant-ligatures: none;"
  , "    }"
  , ""
  , "    /* Chord + lyric rows */"
  , "    .chord-lyric-row {"
  , "      display: flex;"
  , "      flex-wrap: wrap;"
  , "      align-items: flex-end;"
  , "      line-height: 1.35;"
  , "    }"
  , "    .chord-lyric-pair {"
  , "      display: inline-flex;"
  , "      flex-direction: column;"
  , "      white-space: pre;"
  , "    }"
  , "    .chord {"
  , "      color: var(--accent);"
  , "      font-weight: 600;"
  , "      font-size: .88rem;"
  , "      line-height: 1.45;"
  , "      min-height: 1.5em;"
  , "      letter-spacing: .01em;"
  , "      user-select: none;"
  , "    }"
  , "    .chord-custom { color: var(--accent-2); }"
  , "    .chord-spacer { min-height: 1.5em; visibility: hidden; }"
  , "    .lyric { color: var(--ink); white-space: pre; }"
  , "    .chord-only-row {"
  , "      display: flex;"
  , "      gap: 2rem;"
  , "      color: var(--accent);"
  , "      font-weight: 600;"
  , "      padding: .15rem 0;"
  , "    }"
  , "    .lyric-only-row { color: var(--ink); }"
  , ""
  , "    /* Hover diagram popover */"
  , "    .chord-with-hover { position: relative; display: inline-block; cursor: help; }"
  , "    .chord-popover {"
  , "      position: absolute;"
  , "      bottom: calc(100% + 10px);"
  , "      left: 50%;"
  , "      transform: translateX(-50%) translateY(4px);"
  , "      background: var(--paper);"
  , "      border: 1px solid var(--line);"
  , "      border-radius: 6px;"
  , "      padding: .55rem .6rem .45rem;"
  , "      box-shadow: 0 14px 34px -12px var(--shadow);"
  , "      z-index: 100;"
  , "      visibility: hidden;"
  , "      opacity: 0;"
  , "      transition: opacity .16s ease, transform .16s ease, visibility .16s;"
  , "      pointer-events: none;"
  , "    }"
  , "    .chord-popover::after {"
  , "      content: '';"
  , "      position: absolute;"
  , "      top: 100%;"
  , "      left: 50%;"
  , "      transform: translateX(-50%);"
  , "      border: 6px solid transparent;"
  , "      border-top-color: var(--line);"
  , "    }"
  , "    .chord-with-hover:hover .chord-popover {"
  , "      visibility: visible;"
  , "      opacity: 1;"
  , "      transform: translateX(-50%) translateY(0);"
  , "    }"
  , "    .chord-popover-text {"
  , "      width: max-content;"
  , "      max-width: 13rem;"
  , "      padding: .7rem .8rem;"
  , "      color: var(--ink);"
  , "      font-family: var(--sans);"
  , "      font-size: .78rem;"
  , "      line-height: 1.35;"
  , "      text-align: center;"
  , "    }"
  , "    .chord-popover-text strong { display: block; color: var(--accent); margin-bottom: .25rem; }"
  , "    .chord-popover-text span { color: var(--muted); }"
  , "    .chord-diagram-svg { display: block; }"
  , ""
  , "    /* Chord palette footer */"
  , "    .song-chords-palette {"
  , "      margin-top: 3.5rem;"
  , "      padding-top: 1.8rem;"
  , "      border-top: 1px solid var(--line);"
  , "    }"
  , "    .palette-title {"
  , "      font-size: .68rem;"
  , "      font-weight: 600;"
  , "      letter-spacing: .2em;"
  , "      text-transform: uppercase;"
  , "      color: var(--faint);"
  , "      margin-bottom: 1.4rem;"
  , "    }"
  , "    .palette-grid { display: flex; flex-wrap: wrap; gap: .9rem; }"
  , "    .palette-item {"
  , "      border: 1px solid var(--line);"
  , "      border-radius: 4px;"
  , "      padding: .45rem .55rem .3rem;"
  , "      transition: border-color .18s ease, transform .18s ease;"
  , "    }"
  , "    .palette-item:hover { border-color: var(--accent); transform: translateY(-2px); }"
  , ""
  , "    /* Diagram colors follow the active theme */"
  , "    .chord-diagram-svg .grid-line { stroke: var(--line); }"
  , "    .chord-diagram-svg .nut-line { stroke: var(--ink); fill: var(--ink); }"
  , "    .chord-diagram-svg .diag-name { fill: var(--ink); font-family: var(--sans); font-weight: 600; }"
  , "    .chord-diagram-svg .diag-fret { fill: var(--muted); font-family: var(--mono); font-weight: 600; }"
  , "    .chord-diagram-svg .diag-dot { fill: var(--accent); }"
  , "    .chord-diagram-svg .diag-finger { fill: var(--paper); font-family: var(--mono); font-weight: 700; }"
  , "    .chord-diagram-svg .diag-open { stroke: var(--muted); }"
  , "    .chord-diagram-svg .diag-mute { fill: var(--accent-2); font-family: var(--mono); font-weight: 700; }"
  , ""
  , "    @media (max-width: 640px) {"
  , "      body { padding: 1.5rem .75rem; }"
  , "      .sheet { padding: 3rem 1.5rem 2.5rem; }"
  , "      .song-title { font-size: 2rem; }"
  , "    }"
  , "    @media print {"
  , "      /* Always print in light colors, whatever the screen theme is */"
  , "      :root, [data-theme=\"dark\"], [data-theme=\"light\"] {"
  , "        --bg: #ffffff;"
  , "        --paper: #ffffff;"
  , "        --ink: #111111;"
  , "        --muted: #555555;"
  , "        --faint: #888888;"
  , "        --line: #cccccc;"
  , "        --accent: #1a4fa0;"
  , "        --accent-2: #9a6212;"
  , "        --section: #1f6b32;"
  , "        --shadow: transparent;"
  , "      }"
  , "      body { background: #fff; padding: 0; }"
  , "      .sheet { box-shadow: none; border: none; max-width: 100%; padding: 0; }"
  , "      .theme-toggle { display: none; }"
  , "      .chord-popover { display: none; }"
  , "    }"

  ]

-- Inline script: defaults to system preference, persists the user choice.
themeScript :: String
themeScript = unlines
  [ "(function(){"
  , "  var t=null;"
  , "  try{t=localStorage.getItem('chordbook-theme');}catch(e){}"
  , "  if(!t){t=window.matchMedia&&window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';}"
  , "  document.documentElement.setAttribute('data-theme',t);"
  , "})();"
  , "function toggleTheme(){"
  , "  var el=document.documentElement;"
  , "  var next=el.getAttribute('data-theme')==='light'?'dark':'light';"
  , "  el.setAttribute('data-theme',next);"
  , "  try{localStorage.setItem('chordbook-theme',next);}catch(e){}"
  , "}"
  ]
